# On Day-3, we learn about Python buildIn module and external modules. I mean what is the use of them and how can we install them.

# We also get to know about Pip, which is a python package manager and it very easy to use...